### PR TITLE
added a new minimal script as a tutorial

### PR DESCRIPTION
**Pull request by mzaiss**
fixed comment in RLE

### CODE REVIEW

**Comment by mzaiss** [comment]
please merge into master and remove branch

**Comment by mzaiss** [comment]
maybe this extremely simple demo sequence  is also better to use in the demo.mlx file

**Comment by kherz** [comment]
I wouldn't use the which statement for file identification of the standard example files just to save sme lines of code. Could be that there is another one with the same name in a different folder that is higher in the path and that will eventually lead to confusion...

**Comment by mzaiss** [comment]
ok you're the boss.
but this activewindow stuff is weird too.
cant we use which for file like pulseqsim and derive the base path from that?

**Comment by kherz** [comment]
path is no problem i just added a function for that. Just the filename needs the active window to determine the automatic name for the seq file when the section mode is used

**Comment by mzaiss** [comment]
@kherz  du musst das noch reviewen, sonst kann man es nicht mergen, oder?

**Review by kherz — APPROVED** [review]

**Pull request merged**
