### PR TITLE
Fix issue 14

### PR DESCRIPTION
**Pull request by kherz**
see issue #14

### CODE REVIEW

**Comment by kherz** [comment]
i fixed the bug and uploaded the new mex files for windows and linux.
 @mzaiss can anyone compile for mac? 
Besides that, ready to merge

**Review by mzaiss — APPROVED** [review]
i thought both times are needed ringdown and dead time?

**Comment by kherz** [comment]
yes, but deadtime was used twice by accident. Could you generate the mex file for mac yet?

**Comment by mzaiss** [comment]
no, 
i thought you meant linux.
we also do not have access to a mac.

**Pull request merged**
