### PR TITLE
fixed phase/frequency bug

### PR DESCRIPTION
**Pull request by kherz**
Just found a bug regarding the phase/frequency of the rf pulses:
The phase object at the scanner is actually set with -dw\*t and not dw\*t as it was in the simulation code before.
As the -dw and +dw elements in the Bloch matrix were also swapped, this didn't effect the adiabatic spin-lock pulses or the normal saturation pulses. However, the classical spin-lock simulation was wrong as the z-component of Beff was pointing in the negated z-direction. Now the simulation should be correct for all cases.
 TODO: recompile for mac

### CODE REVIEW

**Comment by schuenke** [comment]
Can you attach a seq-file with a conventional SL prep please? Would help me to fix this in the Python Simulation as well.

**Comment by mzaiss** [comment]
I will upload my apt sl

Patrick Schuenke ***@***.***> schrieb am Fr., 30. Juli 2021,
11:59:

**Comment by mzaiss** [comment]
I added the script to the library git and linked there to this commit

**Comment by mzaiss** [comment]
APTw_3T_004_2uT_20SL_DC50_2s_braintumor

looked like that previously

grafik

now looks like this 

grafik


solved

**Comment by schuenke** [comment]
Fixed it in the python BMCTool as well. Currently in the dev branch (https://github.com/schuenke/BMCTool/tree/dev) only, but I will incorporate it in the next release.

**Pull request merged**
